# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# Disable space inside array brackets rule for PDF files
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'app/pdfs/**/*'
    - 'test/pdfs/**/*'
